spring:
  application:
    name: spring-library-management-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: your_url
    username: your_username
    password: your_password
    hikari:
      schema: your_schema
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: your_name
      password: your_password

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 3000000  # 5 minutes in milliseconds
  refresh-token:
    expiration: 3600000  # 1 hour in milliseconds
