spring:
  application:
    name: spring-library-management-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orient
    username: postgres
    password: 1234
    hikari:
      schema: spring
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: 1234

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 3000000  # 5 minutes in milliseconds
  refresh-token:
    expiration: 3600000  # 1 hour in milliseconds
