spring:
  application:
    name: spring-library-management-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    hikari:
      schema: orient
  security:
    user:
      name: pinar
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

